# Generated by Django 2.2.11 on 2020-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcategory',
            name='animalname',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Buffaloe-Cow', 'Buffalo-Cow'), ('Others', 'Others')], max_length=200),
        ),
    ]
