# Generated by Django 2.2.11 on 2020-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_auto_20200309_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermilkcategory',
            name='animalname',
            field=models.CharField(choices=[('Cow', 'Cow'), ('buffalo', 'Buffalo'), ('Others', 'Others')], max_length=200),
        ),
    ]
